defaults:
  start_date: "2018-01-01"
  granularity: daily
  unit: kbd
  only_realized: false
  with_forecast: true
  with_intra_region: true
  with_freight_view: false
  with_product_estimation: false

external:
  with_intra_country: false
  us_zone: United States
  us_import_splits:
    - origin countries
    - origin trading regions
    - products
  us_export_splits:
    - destination countries
    - destination trading regions
    - products
  europe_import_splits:
    - origin countries
    - origin trading regions
    - products
  europe_export_splits:
    - destination countries
    - destination trading regions
    - products

domestic_padd:
  with_intra_country: true
  from_zones:
    - United States
  to_zones:
    - United States
  flow_direction: export
  splits:
    - origin padds
    - destination padds
    - products

balance_guides:
  frequencies:
    weekly: eia-weekly
    monthly: monthly
  pulls:
    diesel_padd1ab_imports_external:
      commodities:
        - diesel
      flow_direction: import
      to_zones:
        - PADD 1 - A
        - PADD 1 - B
      splits:
        - origin countries
      with_intra_country: false
    jet_padd1_imports_external:
      commodities:
        - jet
      flow_direction: import
      to_zones:
        - PADD 1
      splits:
        - origin countries
      with_intra_country: false
    diesel_padd1c_imports_intracountry:
      commodities:
        - diesel
      flow_direction: import
      to_zones:
        - PADD 1 - C
      splits:
        - origin countries
      with_intra_country: false
    diesel_padd1ab_exports_external:
      commodities:
        - diesel
      flow_direction: export
      from_zones:
        - PADD 1 - A
        - PADD 1 - B
      splits:
        - destination trading regions
      with_intra_country: false
    diesel_padd1c_exports_external:
      commodities:
        - diesel
      flow_direction: export
      from_zones:
        - PADD 1 - C
      splits:
        - total
      with_intra_country: false
    jet_padd1_exports_external:
      commodities:
        - jet
      flow_direction: export
      from_zones:
        - PADD 1
      splits:
        - total
      with_intra_country: false
    padd3_exports_external:
      commodities:
        - diesel
        - jet
      flow_direction: export
      from_zones:
        - PADD 3
      splits:
        - destination trading regions
      with_intra_country: false
    padd5_imports_external:
      commodities:
        - diesel
        - jet
      flow_direction: import
      to_zones:
        - PADD 5
      splits:
        - total
      with_intra_country: false
    padd5_exports_external:
      commodities:
        - diesel
        - jet
      flow_direction: export
      from_zones:
        - PADD 5
      splits:
        - total
      with_intra_country: false
    us_imports_external:
      commodities:
        - diesel
      flow_direction: import
      to_zones:
        - United States
      splits:
        - origin countries
      with_intra_country: false
    us_exports_external:
      commodities:
        - diesel
      flow_direction: export
      from_zones:
        - United States
      splits:
        - destination trading regions
      with_intra_country: false
    diesel_padd3_to_padd1ab:
      commodities:
        - diesel
      flow_direction: export
      from_zones:
        - PADD 3
      to_zones:
        - PADD 1 - A
        - PADD 1 - B
      splits:
        - total
      with_intra_country: true
    diesel_padd3_to_padd1c:
      commodities:
        - diesel
      flow_direction: export
      from_zones:
        - PADD 3
      to_zones:
        - PADD 1 - C
      splits:
        - total
      with_intra_country: true
    jet_padd3_to_padd1:
      commodities:
        - jet
      flow_direction: export
      from_zones:
        - PADD 3
      to_zones:
        - PADD 1
      splits:
        - total
      with_intra_country: true
    jet_padd3_to_padd5:
      commodities:
        - jet
      flow_direction: export
      from_zones:
        - PADD 3
      to_zones:
        - PADD 5
      splits:
        - total
      with_intra_country: true
